<?php

/**
 * @file
 * Contains commerce_checkout_api.module.
 */

use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\user\RoleInterface;

/**
 * Implements hook_help().
 */
function commerce_checkout_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_checkout_api module.
    case 'help.page.commerce_checkout_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function commerce_checkout_api_theme() {
  return [
    'commerce_checkout_api' => [
      'render element' => 'children',
    ],
  ];
}


/**
 * Implements hook_install().
 */
function commerce_checkout_api_install()
{
    // 为已认证用户添加权限
    user_role_grant_permissions(RoleInterface::AUTHENTICATED_ID, [
        'create own customer profile',
        'view own customer profile',
        'update own customer profile',
        'delete own customer profile'
    ]);
}

/**
 * Implements hook_entity_base_field_info().
 */
function commerce_checkout_api_entity_base_field_info(EntityTypeInterface $entity_type) {
    $fields = [];
    if ($entity_type->id() == 'commerce_order') {

        $fields['contact'] = BaseFieldDefinition::create('entity_reference')
            ->setLabel(t('联系信息'))
            ->setSetting('target_type', 'profile')
            ->setSetting('handler', 'default')
            ->setDisplayOptions('view', [
                'label' => 'above',
                'type' => 'entity_reference_entity_view'
            ])
            ->setDisplayOptions('form', [
                'type' => 'inline_entity_form_simple'
            ])
            ->setDisplayConfigurable('view', true)
            ->setDisplayConfigurable('form', true);
    }
    return $fields;
}

/**
 * Implements hook_entity_bundle_field_info().
 */
function commerce_checkout_api_entity_bundle_field_info(EntityTypeInterface $entity_type, $bundle, array $base_field_definitions)
{
    if ($entity_type->id() == 'profile' && $bundle == 'customer') {
        $fields = [];
        $fields['phone'] = \Drupal\entity\BundleFieldDefinition::create('string')
            ->setLabel(t('联系电话'))
            ->setDefaultValue('')
            ->setDisplayOptions('view', [
                'label' => 'inline',
                'type' => 'string'
            ])
            ->setDisplayOptions('form', [
                'type' => 'string_textfield'
            ])
            ->setDisplayConfigurable('view', true)
            ->setDisplayConfigurable('form', true);

        return $fields;
    }
}

/**
 * Implements hook_entity_field_storage_info().
 */
function commerce_checkout_api_entity_field_storage_info(EntityTypeInterface $entity_type) {
    if ($entity_type->id() == 'profile') {
        $definitions['phone'] = \Drupal\entity\BundleFieldDefinition::create('string')
            ->setName('phone')
            ->setLabel(t('联系电话'))
            ->setTargetEntityTypeId($entity_type->id());
        return $definitions;
    }
}

/**
 * Implements hook_entity_type_build().
 */
function commerce_checkout_api_entity_type_build(array &$entity_types) {
    /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
    if (isset($entity_types['profile'])) {
        $entity_types['profile']->setHandlerClass('inline_form', '\Drupal\commerce_checkout_api\Form\ProfileInlineForm');
    }
}